source ~/.vim/vimrcs/plugins.vim


" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'

Plug 'itchyny/lightline.vim'

" Initialize plugin system
call plug#end()

set nu

set laststatus=2
set noshowmode
